/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:9135ebb0-5e67-4ce2-b115-dc305ce347e6",
    "aws_cognito_region": "eu-west-1",
    "oauth": {}
};


export default awsmobile;
